### ISSUE TITLE
Protection for capital letters ignored in some cases

### ISSUE THREAD

**Issue by 0xdf** [josephwright/biblatex-ieee#19]
Hi,

I am having the problem, that protection for capital letters is ignored in some cases. E.g. in the record

    title = {{PUCA}: A pseudonym scheme with strong privacy guarantees for vehicular ad-hoc networks},

is rendered as 

    “Puca: A pseudonym scheme with strong privacy guarantees for vehicular ad-hoc networks”, 

I am using the biblatex-ieee style with the following command

    \usepackage[style=ieee,backend=biber,defernumbers=true]{biblatex}

There's a more detailed description about the problem and a hint what might cause it at http://tex.stackexchange.com/questions/233971/biblatex-ieee-ignores-protection-for-capital-letters-in-title.

Cheers,
David

**Comment by 0xdf** [comment]
Nevermind, this seems to be fixed in the latest version according to the changelog.

**Comment by josephwright** [comment]
Dupe of https://github.com/josephwright/biblatex-ieee/issues/18
