### ISSUE TITLE
Repeated author names should be replaced by a dash

### ISSUE THREAD

**Issue by josephwright** [josephwright/biblatex-ieee#2]
As subject!

**Comment by koppor** [comment]
Is it possible to have this configurable? `IEEEtran.bst` reads as follows:

```
% #0 turns off the "dashification" of repeated (i.e., identical to those
% of the previous entry) names. The IEEE normally does this.
% #1 enables
FUNCTION {default.is.dash.repeated.names} { #1 }
```

I am aware that this configuration option is not propagated to the user, but IMHO it should. Most persons are unused to the dash thing and just want to use the IEEE style for other cases (refs https://github.com/josephwright/biblatex-ieee/pull/22#issuecomment-206542227).

**Comment by josephwright** [comment]
@koppor You just have to alter the defintiion of `\bibnamedash` as in the standard styles
