### ISSUE TITLE
Capitalization Issue for title={{Some title}} for book entires

### ISSUE THREAD

**Issue by tfechner** [josephwright/biblatex-ieee#24]
Hi,

I've stumbled across an odd behavior in the latest version of biblatex-ieee (v1.1m).
After compiling with biber and biblatex-ieee book titles are all capitalized for book entries, but only if the title is enclosed in two curly brackets.

The easiest way to recreate it is to change one of the given examples in [biblatex-ieee.bib](https://github.com/josephwright/biblatex-ieee/blob/master/biblatex-ieee.bib)
Original that works as intendend:
```
@book{IEEEexample:inbookpagesnote,
  author        = "B. K. Bul",
  title         = "Theory Principles and Design of Magnetic Circuits",
  publisher     = "Energia Press",
  loction       = "Moscow",
  year          = "1964",
  pages         = "464",
  note          = "(in Russian)"
}
```
Result
![image](https://cloud.githubusercontent.com/assets/1140542/14978276/11a5f7ce-111b-11e6-8e8b-b85dff473c03.png)

Changed title field with double \{{ \}} brackets.
```
@book{IEEEexample:inbookpagesnote,
  author        = "B. K. Bul",
  title         = {{Theory Principles and Design of Magnetic Circuits}},
  publisher     = "Energia Press",
  loction       = "Moscow",
  year          = "1964",
  pages         = "464",
  note          = "(in Russian)"
}
```
Result 
![caps](https://cloud.githubusercontent.com/assets/1140542/14977870/1e322588-1118-11e6-87b2-0b7a97d1a9ba.PNG)
After compiling the example [biblatex-ieee.tex](https://github.com/josephwright/biblatex-ieee/blob/master/biblatex-ieee.tex) with the changed .bib file the title is completely in caps. But only if the title element is enclosed in curly brackets and only for book elements as far as I can tell. 

EDIT: 
* Miktex 2.9
* biblatex 3.3
* biblatex-ieee 1.1m
* biber backend from 2016-03-09, .bbl file tells me it is 2.6

This behavior might be linked to a previous [issue#18](https://github.com/josephwright/biblatex-ieee/issues/18).

**Comment by josephwright** [comment]
This is all 'works for me': I'll need a full MWE and a `.log` file.

**Comment by tfechner** [comment]
Sure, I hope you don't mind that I have butchered your documentation of the package fo the MWE.

MWE of biblatex-ieee.tex 
```
\documentclass[a4paper]{ltxdoc}
\usepackage[style=ieee,backend=biber]{biblatex}

\addbibresource{biblatex-ieee.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

MWE for biblatex-ieee.bib with a couple of different types for demonstration
```
@inbook{IEEEexample:incollectionwithseries,
  author        = "J. B. Anderson and K. Tepe",
  title         = {{Properties of the Tailbiting {BCJR} Decoder}},
  booktitle     = {{Codes, Systems and Graphical Models}},
  series        = "{IMA} Volumes in Mathematics and Its Applications",
  publisher     = "Springer-Verlag",
  location      = "New York",
  year          = "2000"  
}

@book{IEEEexample:inbookpagesnote,
  author        = "B. K. Bul",
  title         = {{Theory Principles and Design of Magnetic Circuits}},
  publisher     = "Energia Press",
  loction       = "Moscow",
  year          = "1964",
  pages         = "464",
  note          = "(in Russian)"
}

@book{IEEEexample:bookwitheditor,
  editor        = "J. C. Candy and G. C. Temes",
  title         = {{Oversampling Delta-Sigma Data Converters Theory,
                   Design and Simulation}},
  publisher     = "{IEEE} Press.",
  location      = "New York",
  year          = "1992"
}

@article{IEEEexample:articlelargepages,
  author        = "A. Castaldini and A. Cavallini and B. Fraboni
                   and P. Fernandez and J. Piqueras",
  title         = {{Midgap Traps Related to Compensation Processes in
                   {CdTe} Alloys}},
  journaltitle  = "Phys. Rev. B.",
  volume        = "56",
  number        = "23",
  year          = "1997",
  pages         = "14897-14900"
}

@inproceedings{IEEEexample:presentedatconf,
  author        = "S. G. Finn and M. M{\'e}dard and R. A. Barry",
  title         = {{A Novel Approach to Automatic Protection Switching
                   Using Trees}},
  eventtitle    = "{IEEE} International Conference on Communications",
  location      = "Montreal, Que., Canada",
  year          = "1997"
}
```
This is the result the MWE.
![image](https://cloud.githubusercontent.com/assets/1140542/15096917/c96ccbfa-150b-11e6-888a-e6f6388c8332.png)

The .log is in the attachment as are the files for the MWE - they are zipped [mwe.zip](https://github.com/josephwright/biblatex-ieee/files/253832/mwe.zip)

Thank you for looking into this!

**Comment by josephwright** [comment]
I think I've tracked this down: I'll update the release with a fix.

**Comment by tfechner** [comment]
Thanks - that has fixed the issue!
