### ISSUE TITLE
Link to Style Manual is broken

### ISSUE THREAD

**Issue by sappjw** [josephwright/biblatex-ieee#26]
The link to the style manual in the documentation is broken.  I believe the intent is to link to [https://www.ieee.org/documents/ieeecitationref.pdf](https://www.ieee.org/documents/ieeecitationref.pdf) or possibly [https://www.ieee.org/documents/style_manual.pdf](https://www.ieee.org/documents/style_manual.pdf).

**Comment by BartLH** [comment]
These documents have moved again. The new locations are http://ieeeauthorcenter.ieee.org/wp-content/uploads/IEEE_Style_Manual.pdf and https://ieee-dataport.org/sites/default/files/analysis/27/IEEE%20Citation%20Guidelines.pdf. The first is probably the preferred source to put in the package documentation.
