### ISSUE TITLE
Compressed reference bracket format does not match Style Manual

### ISSUE THREAD

**Issue by sappjw** [josephwright/biblatex-ieee#27]
On page 34 of the [IEEE Editorial Style Manual](https://www.ieee.org/documents/style_manual.pdf), it shows examples of compressed references as `[1]--[5]`, but this package seems to default to `[1--5]`.  It might be best to format compressed references as indicated in these examples.

**Comment by josephwright** [comment]
There was a bug here, but not as you describe: I'd managed to kill the compression entirely! I've fixed that in v1.1p: can you test that and post an example if it fails.

**Comment by sappjw** [comment]
v1.1p seems to resolve this issue.  Thanks!
