### ISSUE TITLE
Book titles seem to be inconsistent with style guide

### ISSUE THREAD

**Issue by mykelk** [josephwright/biblatex-ieee#28]
Compare reference [2] here:
http://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-ieee/biblatex-ieee.pdf
with reference [1] of the book examples:
https://www.ieee.org/documents/ieeecitationref.pdf

Am I missing something?

**Comment by malaverdiere** [comment]
The basic format is:
`J. K. Author, “Title of chapter in the book,” in  Title of His Published Book, x th ed. City of Publisher, Country if not USA: Abbrev. of Publisher, year, ch. x , sec. x , pp. xxx–xxx. `
However, many of those fields are optional.
The citation you gave is:
`B. K. Bul, Theory principles and design of magnetic circuits. Energia Press, 1964, p. 464, (in Russian).`
So that looks fine, although the publisher city (and country) is missing and shouldn't.

**Comment by josephwright** [comment]
There's a typo in the `.bib` file for the entry for Bul: I'll fix that. If you look at the example for Candy, for example, it looks OK.

**Comment by mykelk** [comment]
I think the issue is the capitalization of the book. The IEEE style has book titles as titlecase (and chapter titles sentence case), whereas it looks like biblatex-ieee has both as sentence case. The title case in the IEEE spec is indicated by "Title of His Published Book" (first letter in each word is caps).

**Comment by josephwright** [comment]
I'm thinking about this!

**Comment by mykelk** [comment]
Are you sure this is resolved? The book title capitalization doesn't seem to work properly for me. Here is my log indicating the version:
```
Package biblatex Info: Trying to load bibliography style 'ieee'...
Package biblatex Info: ... file 'ieee.bbx' found.
 (./ieee.bbx
File: ieee.bbx 2016/12/30 vvv1.2 biblatex bibliography style
```

**Comment by josephwright** [comment]
@mykelk Can you post an example showing the issue you are seeing? My tests looked OK so perhaps I'm missing something.

**Comment by mykelk** [comment]
Yep. Here is a minimal example:
[test.zip](https://github.com/josephwright/biblatex-ieee/files/722138/test.zip)
It looks like this:
![image](https://cloud.githubusercontent.com/assets/6294079/22184634/9f1fc992-e08a-11e6-8f4c-fb817dc4db5a.png)

**Comment by josephwright** [comment]
Running the example in:
```latex
\RequirePackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@Book{Kochenderfer2015,
  Title                    = {Decision Making Under Uncertainty: Theory and Application},
  Author                   = {Mykel J. Kochenderfer},
  Publisher                = {MIT Press},
  Year                     = {2015}
}
\end{filecontents*}
\documentclass{article}
\usepackage[style=ieee]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

**Comment by mykelk** [comment]
If we could just use the same kind of capitalization scheme as journal article titles, I think we'd be set.
