### ISSUE TITLE
Better defaults for biburl*penalties

### ISSUE THREAD

**Issue by languitar** [josephwright/biblatex-ieee#29]
With the narrow columns in the IEEE layout, longer URLs in the bibliography are usually rendered with very wide space. Maybe it would be possible to provide better defaults for the various biburl*penalty counters for use with this package?

**Comment by josephwright** [comment]
The standard values from `biblatex` make sense for a typical one column document, and that's true for the IEEE styles as well as others. There's no link between the bibliography style and a decision to use a two-column format: as such, this isn't the 'right' place to address this.
