### ISSUE TITLE
dashed option missing

### ISSUE THREAD

**Issue by millo-k** [josephwright/biblatex-ieee#30]
Please provide the dashed option to deactivate the dash for recurring authors and editors.

**Comment by josephwright** [comment]
The IEEE styles (as used by the IEEE) are numeric so omitting authors doesn't make a lot of sense. Yes, one can mix-and-match with `biblatex` but I'm reluctant to go this way (styles following a particular publisher should take a strong lead from the relevant body).

**Comment by josephwright** [comment]
I've thought about this: the current behaviour matches the 'parent' styles from the `biblatex` core, and I'm not minded to change.

**Comment by niklasdoose** [comment]
The commit seems to only add the dashed option to the `ieee` style and not to the `ieee-alphabetic` style. Is there a reason for this/could you add the option to the `ieee-alphabetic` style?
