### ISSUE TITLE
ISSN fields for journal articles.

### ISSUE THREAD

**Issue by nonkreon** [josephwright/biblatex-ieee#33]
Dear Mr. Wright,
Allow me to thank for your efforts on this package first. I see that the package prints the ISSN fields for journal articles, which is not to be done as directed by IEEE. 
Thanks a lot!

**Comment by josephwright** [comment]
This should be governed by the `isbn` option as for standard `biblatex` styles: can you provide a MWE?

**Comment by josephwright** [comment]
No further update: closing.
