### ISSUE TITLE
Unwanted linebreak after bibstring and before field 

### ISSUE THREAD

**Issue by udopt** [josephwright/biblatex-ieee#34]
In [ieee.bbx](https://github.com/josephwright/biblatex-ieee/blob/a76e6a2ed72c8c663e72f1848d9d08a738593218/ieee.bbx#L360), `\addspace` is used to separate the bibstring `number` and the field `number`. The same is true for the [volume](https://github.com/josephwright/biblatex-ieee/blob/a76e6a2ed72c8c663e72f1848d9d08a738593218/ieee.bbx#L352) and maybe other fields as well.

This can lead to unwanted line breaks between the bibstring and the field. I manually replaced `\addspace` by `\addnbspace`, maybe this could be the default behaviour or a package option.

**Comment by josephwright** [comment]
Probably the formatting should be applied at the `\DeclareFieldFormat` stage in any case, with the bibmacro just putting in the correct fields with no hard-coded formatting. I'll adjust.

**Comment by josephwright** [comment]
Fixed I hope by https://github.com/josephwright/biblatex-ieee/commit/6db5cd40886a59d9e23e2ed8b912eb177bbbf9a0
