### ISSUE TITLE
doi wrongly printed capitalized

### ISSUE THREAD

**Issue by 7Z0t99** [josephwright/biblatex-ieee#36]
Hi, I'm running TeXlive 2016 on Windows with biblatex-ieee 1.2 (texlive rev 42818).
When I add the doi field to one of my references, it prints as DOI: [DOI number], but when I look into the IEEE citation reference, it says that it should be doi: [DOI number]. Please note the uppercase vs. lowercase.
Is an easy fix / workaround possible?

Thank you very much!

**Comment by josephwright** [comment]
I've checked the citation reference doc and it doesn't seem to be self-consistent: they refer to DOIs but then suggest 'doi' for formatting! Do you have any 'in the wild' examples you can point to? (In the end I favour going with practice in set journals over style guides.)

**Comment by 7Z0t99** [comment]
No, I have never seen that in an IEEE journal. I want to cite an early access journal article of another publisher (Wiley) and they suggest adding the doi in this case. I know that there is to appear and to be published, but that doesn't apply here since the article is already published - albeit only online.
When you export the citation for an IEEE early access article, it will typically say vol. PP as a special indicator, but using the same scheme for another publisher doesn't make sense in my eyes.

To be honest, I think IEEE don't completely follow their citation guide since it says one should use the doi for conference articles without page numbers, but I routinely see conference proceedings on IEEExplore whose articles' citations will tell you: page 1--x - and a lot of people will just use that (and not the doi). :-)

**Comment by josephwright** [comment]
You likely want something of the form
```latex
\DeclareFieldFormat{doi}{%
  doi\addcolon
  \ifhyperref
    {\href{http://dx.doi.org/#1}{\nolinkurl{#1}}}
    {\nolinkurl{#1}}%
}
```
(used in the `nature` style). I'm reluctant to change the distributed code here unless it is clear that the IEEE actually do what they say they do!

**Comment by 7Z0t99** [comment]
Thank you very much. I still added a space after the colon and removed the period at the end, but now it works

**Comment by josephwright** [comment]
For the present closing as it's not clear I can make a change here!

**Comment by 7Z0t99** [comment]
@josephwright I recently ran into the first IEEE paper I saw using dois: [https://doi.org/10.1109/TCSII.2017.2764460]
However I find it strange that reference 13 has got both, a doi and a url
