### ISSUE TITLE
smaller font size must be used for the reference list

### ISSUE THREAD

**Issue by afcuttin** [josephwright/biblatex-ieee#37]
If I use this style with BibLaTeX, the _references_ section is typeset using the same font size as the normal text (font size 10).
Instead,  a smaller font size must be used (font size 8), as in the IEEEtran.bst file provided with the IEEEtran class.

The recommended font sizes are given here: http://paginas.fe.up.pt/~jca/wrsc/templates/IEEE-Conference-A4-format.pdf

**Comment by josephwright** [comment]
All true, but that's a feature of the _document class_ not the _bibliography style_.

**Comment by afcuttin** [comment]
So you think that the font size must be set separately?

**Comment by josephwright** [comment]
@afcuttin It's not part of the _bibliography style_ (which is things like the ordering and formatting of fields), so 'yes'. You can use the IEEE bibliography style for lots of things: in a thesis for example the document will be one column and have larger text than in a paper ...

**Comment by afcuttin** [comment]
I see and I may agree, nevertheless, if I switch to bibtex, the references section is formatted properly
