### ISSUE TITLE
header set when references span pagebreak

### ISSUE THREAD

**Issue by 7Z0t99** [josephwright/biblatex-ieee#39]
Usually using biblatex-ieee together with IEEEtran in journal mode works fine, but sometimes my references start on one page and continue on the next. In this case, "REFERENCES" appears in the page header, which I consider a bug. 

Can this be fixed in biblatex-ieee or does IEEEtran need a modification?

**Comment by 7Z0t99** [comment]
Here is an example tex file to reproduce. Unfortunately Github doesn't allow me to upload a bib or tex file, so I zipped them. 
[example.zip](https://github.com/josephwright/biblatex-ieee/files/1369580/example.zip)

**Comment by josephwright** [comment]
The style does nothing 'special' in terms of headings: this is all handled by standard LaTeX constructs. At the same time, the demo doesn't show the issue for me. As such, this doesn't look valid.
