### ISSUE TITLE
provide example of how to produce a correct IEEE document (font size for reference list)

### ISSUE THREAD

**Issue by muelli** [josephwright/biblatex-ieee#49]
Given that https://github.com/josephwright/biblatex-ieee/issues/37 is marked as "wontfix" I am left wondering how to produce a document with the IEEEtran class (in conference mode) that adheres to the IEEE style.

I expected to simply use the ieee style for biblatex and be done with it, but that is obviously not the case as the bibliography is typeset with a 9 or 10 point font rather than a smaller 8 point font.

My life would have been a bit happier if there was such an example document or at least instructions that I have to put `\renewcommand*{\bibfont}{\footnotesize}` in my header.

**Comment by josephwright** [comment]
For conference submission you _have_ to use their class if available, which means using classical BibTeX not `biblatex`.
