### ISSUE TITLE
Upcoming changes to numeric-comp for subentrycomp

### ISSUE THREAD

**Issue by moewew** [josephwright/biblatex-ieee#51]
Since plk/biblatex#900 changed some bits and pieces of `numeric-comp.cbx` `ieee.cbx` will need to be updated for the next `biblatex` version.

The modifications from the following MWE should hopefully do what `ieee.cbx` currently does
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=numeric-comp, backend=biber]{biblatex}


\makeatletter
\DeclareCiteCommand{\cite}%
  {\usebibmacro{cite:init}%
   \bibopenbracket
   \usebibmacro{prenote}}
  {\usebibmacro{citeindex}%
   \usebibmacro{cite:comp}}
  {}
  {\usebibmacro{cite:dump}%
   \usebibmacro{postnote}%
   \bibclosebracket
  }

% The second step is to replace \multicitedelim with a version wrapped in
% the appropriate delimiter.
\renewcommand*{\do}[1]{%
  \expandafter\patchcmd\expandafter
    {\csname abx@macro@\detokenize{#1}\endcsname}%
    {\multicitedelim}
    {\bibclosebracket\multicitedelim\bibopenbracket}
    {}
    {%
      \PackageError{biblatex-ieee}{Failed to update citation style}\@ehc
    }%
  }

\docsvlist{cite:comp:end,cite:comp:inset,cite:dump}

% There's also one \bibrangedash to alter.
\expandafter\patchcmd\expandafter
  {\csname abx@macro@\detokenize{cite:dump}\endcsname}%
  {\multiciterangedelim}
  {\bibclosebracket\multiciterangedelim\bibopenbracket}
  {}
  {%
    \PackageError{biblatex-ieee}{Failed to update citation style}\@ehc
  }%

% More bracket removal required
\DeclareMultiCiteCommand{\cites}{\cite}{\multicitedelim}
\makeatother


\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson,worman,geer,nussbaum}
\printbibliography
\end{document}
```

If I don't forget about it, I may open a pull request to be merged when `biblatex` is updated.

**Comment by moewew** [comment]
What is the IEEE's stance on set citations? Are they cited as

> [1a,b]

or

> [1a,1b]

or

> [1a], [1b]

what about ranges?

> [1a-c]

> [1a-1c]

> [1a]-[1c]

**Comment by josephwright** [comment]
Each number is in brackets, so `[1a],[1b]` and `[1a]-[1c]`

**Comment by moewew** [comment]
With the help of https://github.com/plk/biblatex/commit/fa6b52e9a384d33b24513d97889ca638eb204ce1 I'll hopefully have something ready tonight.

**Comment by moewew** [comment]
Opened https://github.com/josephwright/biblatex-ieee/pull/52 with a suggestion to rework the style. I hope that `numeric-comp` is stable and that this suggestion works for the next release, but I suggest you wait with merging until we can be sure what `biblatex` 3.15 brings.

**Comment by moewew** [comment]
#52 was not a good idea. A new attempt is at #53.
