### ISSUE TITLE
Formatting Issue

### ISSUE THREAD

**Issue by ajaichemmanam** [josephwright/biblatex-ieee#57]
I get every attributes in new line when using biblatex-ieee

[8]    S. Ren, K. He, R. Girshick, and J. Sun, 
“Faster r-cnn: Towards real-time object detection with region proposal networks,”
InAdvances in neural information processing systems,
2015,
Pp. 91–99.

[9]    J. Redmon, S. Divvala, R. Girshick, and A. Farhadi,
“You only look once: Unified, real-time object detection,”
InProceedings of the IEEE conference on computer vision and pattern recognition,
2016,
Pp. 779–788

How to format them to be on the same line? Year and pages in different lines seems awkward and is taking too much space for large bibliographies

Expected output

[9]    J. Redmon, S. Divvala, R. Girshick, and A. Farhadi, “You only look once: Unified, real-time object detection,”
InProceedings of the IEEE conference on computer vision and pattern recognition, 2016, Pp. 779–788

**Comment by josephwright** [comment]
I'll need an example

**Comment by ajaichemmanam** [comment]
Thanks for replying.
Eg.
<img width="402" alt="format" src="https://user-images.githubusercontent.com/10387750/93001152-a30acb00-f54a-11ea-9065-78fbd8436fc3.png">

@inproceedings{yu2016unitbox,
	title     = {Unitbox: An advanced object detection network},
	author    = {Yu, Jiahui and Jiang, Yuning and Wang, Zhangyang and Cao, Zhimin and Huang, Thomas},
	booktitle = {Proceedings of the 24th ACM international conference on Multimedia},
	pages     = {516--520},
	year      = {2016}
}

**Comment by josephwright** [comment]
I mean an example of your TeX input: this looks like you are redefining `\newblock` to me.

**Comment by ajaichemmanam** [comment]
This is how I used inside tex file. The references.bib file contained the reference data.
\usepackage[sorting=none,bibstyle=ieee, backend=biber]{biblatex}
\addbibresource{references.bib}
Unitbox \cite{yu2016unitbox} suggested ....
\printbibliography

Output is given in previous comment. 
I don't know how to explain it to you more.

**Comment by josephwright** [comment]
I have no issue with
```latex
\listfiles
\documentclass{article}
\begin{filecontents}{\jobname.bib}
@inproceedings{yu2016unitbox,
title = {Unitbox: An advanced object detection network},
author = {Yu, Jiahui and Jiang, Yuning and Wang, Zhangyang and Cao, Zhimin and Huang, Thomas},
booktitle = {Proceedings of the 24th ACM international conference on Multimedia},
pages = {516--520},
year = {2016}
}
\end{filecontents}
\usepackage[sorting=none,bibstyle=ieee, backend=biber]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
Unitbox \cite{yu2016unitbox} suggested ....
\printbibliography
\end{document}
```
and `\listfiles` reports
```
*File List*
 article.cls    2019/12/20 v1.4l Standard LaTeX document class
  size10.clo    2019/12/20 v1.4l Standard LaTeX file (size option)
biblatex.sty    2020/08/23 v3.15a programmable bibliographies (PK/MW)
pdftexcmds.sty    2020-06-27 v0.33 Utility functions of pdfTeX for LuaTeX (HO)
infwarerr.sty    2019/12/03 v1.5 Providing info/warning/error messages (HO)
   iftex.sty    2020/03/06 v1.0d TeX engine tests
 ltxcmds.sty    2019/12/15 v1.24 LaTeX kernel commands for general use (HO)
etoolbox.sty    2020/08/24 v2.5j e-TeX tools for LaTeX (JAW)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
kvoptions.sty    2019/11/29 v3.13 Key value format for package options (HO)
kvsetkeys.sty    2019/12/15 v1.18 Key value parser (HO)
  logreq.sty    2010/08/04 v1.0 xml request logger
  logreq.def    2010/08/04 v1.0 logreq spec v1.0
  ifthen.sty    2014/09/29 v1.1c Standard LaTeX ifthen package (DPC)
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
  blx-dm.def    2020/08/23 v3.15a biblatex localization (PK/MW)
blx-compat.def    2020/08/23 v3.15a biblatex compatibility (PK/MW)
   expl3.sty    2020-09-06 L3 programming layer (loader) 
l3backend-pdftex.def    2020-09-01 L3 backend support: PDF output (pdfTeX)
  xparse.sty    2020-05-15 L3 Experimental document command parser
xparse-generic.tex
blx-case-expl3.def
biblatex.def    2020/08/23 v3.15a biblatex compatibility (PK/MW)
standard.bbx    2020/08/23 v3.15a biblatex bibliography style (PK/MW)
 numeric.bbx    2020/08/23 v3.15a biblatex bibliography style (PK/MW)
numeric-comp.bbx    2020/08/23 v3.15a biblatex bibliography style (PK/MW)
    ieee.bbx    2020/08/31 v1.3c biblatex bibliography style
 numeric.cbx    2020/08/23 v3.15a biblatex citation style (PK/MW)
biblatex.cfg    
 english.lbx    2020/08/23 v3.15a biblatex localization (PK/MW)
    test.bbl
 ***********
```

What do you get for that?

**Comment by ajaichemmanam** [comment]
It works without issue. I think I have found the issue.
https://tex.stackexchange.com/questions/56628/custom-references-page-with-additional-line-breaks
Its because of the openbib. I changed from bibtex to biblatex.
Thanks for your time.
