### ISSUE TITLE
Problem with Conference Paper

### ISSUE THREAD

**Issue by StephanGen** [josephwright/biblatex-ieee#58]
Hi, 

I have a Problem with the display of a conference paper in my bibliography (see picture). The citation in my .bib file looks like this:

@inproceedings{tukorFormationWCrPhasesProduction2009,
  title = {Formation of {{W}}-{{Cr}}-{{Phases During}} the {{Production}} of {{Cr}}-Doped {{WC Powders}}},
  author = {Tükör, Z. and Schubert, Wolf-Dieter and Bicherl, A. and Bock, A. and Zeiler, B.},
  date = {2009},
  location = {{Reutte}},
  abstract = {Chromium additions to tungsten powder are known to inhibit WC particle growth during carburisation. However, the role of chromium during the processing is not clarified. To investigate the behaviour of chromium during carburization different reaction paths were investigated (W+Cr3C2+C and WC+Cr3C2+C) to synthesize the phases of the W-Cr-C system along the WC-Cr3C2-section. The results are compared to the known phase diagrams and discussed in relation to the production of chromiumdoped tungsten carbide powder. A metastable (W,Cr)C phase with higher chromium contents as hitherto reported ((W0.85Cr0.15)C; 5wt\% “CrC” resp.) was observed. The stability of this phase was studied at different annealing temperatures.},
  eventtitle = {17. {{Plansee Seminar}}},
  file = {C\:\\Users\\mail\\Zotero\\storage\\K79T2ICE\\Tükör et al. - Formation of W-Cr-Phases During the Production of .pdf}
}

![image](https://user-images.githubusercontent.com/11254604/100984074-80d18980-354a-11eb-84c6-38cb42034533.png)

**Comment by josephwright** [comment]
Can you post your log files? This doesn't look quite right to me: my test file looks OK here.

**Comment by StephanGen** [comment]
[Log.log](https://github.com/josephwright/biblatex-ieee/files/5657424/Log.log)

**Comment by josephwright** [comment]
I tried a shortened example
```latex
\begin{filecontents*}{\jobname.bib}
@inproceedings{tukorFormationWCrPhasesProduction2009,
title = {Formation of {W}-{Cr}-{Phases During} the {Production} of {Cr}-Doped {WC Powders}},
author = {Tükör, Z. and Schubert, Wolf-Dieter and Bicherl, A. and Bock, A. and Zeiler, B.},
date = {2009},
location = {Reutte},
eventtitle = {17. {Plansee Seminar}},
}
\end{filecontents*}

\documentclass{article}
\usepackage[style=ieee]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
Hello
\nocite{*}

\printbibliography

\end{document}
```
and all works fine. Please try that and see what you get.

**Comment by StephanGen** [comment]
So had some time off during the holidays and have now worked on the topic. The shortened example works. When I am replacing the main .bib file of my document with the exact same citation of your example it still plots "presentedat".

**Comment by Hedius** [comment]
The problem triggers if you set a different language than English for your document. presentdate is not defined for other languages.

```
\DefineBibliographyStrings{english}{
  andothers   = \mkbibemph{et al\adddot}           ,
  chapter     = ch\adddot                          ,
  editor      = Ed\adddot                          ,
  editors     = Eds\adddot                         ,
  mathesis    = M\adddot S\adddot\addspace thesis  ,
  patentjp    = Japanese Patent                    ,
  patentus    = U\adddot S\adddot\addspace Patent  ,
  phdthesis   = Ph\adddot D\adddot\addspace dissertation,
  presentedat = presented at the\addspace          ,
  techreport  = Tech\adddot\addspace Rep\adddot    ,
  url         = [Online]\adddot\addspace Available ,
}

\DefineBibliographyStrings{english}{
  june      = Jun\adddot ,
  july      = Jul\adddot ,
  september = Sep\adddot ,
}
```
