### ISSUE TITLE
Make dashed=false the default

### ISSUE THREAD

**Issue by moewew** [josephwright/biblatex-ieee#60]
Via https://tex.stackexchange.com/q/590613/35864

Since the `dashed` option was added for https://github.com/josephwright/biblatex-ieee/issues/30 it has effectively been turned on even though as was rightly pointed out, it does not make much sense for unsorted numeric styles. Just to make sure I checked the current guide https://ieeeauthorcenter.ieee.org/wp-content/uploads/IEEE-Reference-Guide.pdf and a few published papers https://doi.org/10.1109/OJEMB.2021.3053215 (check references 7 & 8 and 14 & 15) and there is no mention or use of dash for repeated authors.

So I suggest you add an explicit `dashed=false,` to the `\ExecuteBibliographyOptions` block. Users who want `dashed` now need to enable it explicitly.

**Comment by moewew** [comment]
As an aside, I just realised that `ieee.bbx` only activates the dash for the `author` macro, which means it does not work for `editor`s or `translator`s in author position. `authortitle.bbx` contains further definitions for that

https://github.com/plk/biblatex/blob/eeae027fdda9b5d278712159d75bdc83f7fa96f8/tex/latex/biblatex/bbx/authortitle.bbx#L67-L117

**Comment by josephwright** [comment]
> As an aside, I just realised that `ieee.bbx` only activates the dash for the `author` macro, which means it does not work for `editor`s or `translator`s in author position. `authortitle.bbx` contains further definitions for that
> 
> https://github.com/plk/biblatex/blob/eeae027fdda9b5d278712159d75bdc83f7fa96f8/tex/latex/biblatex/bbx/authortitle.bbx#L67-L117

I'm honestly not sure what the official formatting should be here.

**Comment by Rmano** [comment]
Last time I submitted a paper to IEEE (quite recently... couple of weeks ago) it was quite clear that they required full references always - no time to find the reference (eh!) now, but I think that you should never use dashes in IEEE styles.

**Comment by Rmano** [comment]
Found this: 
https://www.bath.ac.uk/publications/library-guides-to-citing-referencing/attachments/ieee-style-guide.pdf

**Comment by josephwright** [comment]
@Rmano The official IEEE BibTeX style (https://ctan.org/pkg/ieeetran) uses dashes for repeated authors.

**Comment by Rmano** [comment]
Better link: https://ieeeauthorcenter.ieee.org/wp-content/uploads/IEEE-Reference-Guide.pdf

**Comment by moewew** [comment]
Indeed, http://mirrors.ctan.org/macros/latex/contrib/IEEEtran/bibtex/IEEEtran_bst_HOWTO.pdf has a dashed reference (67). But I don't think dashed make a lot of sense for unsorted styles. You simply won't get the same names consecutively that often.

**Comment by josephwright** [comment]
In the end this is the IEEE's call, and it's what they do. I think it's not unreasonable to expect repeated names: in my area, you tend to cite a whole load of the work of one group in a block, so you'd see repeated names there, for example.

**Comment by Rmano** [comment]
> In the end this is the IEEE's call, and it's what they do. I think it's not unreasonable to expect repeated names: in my area, you tend to cite a whole load of the work of one group in a block, so you'd see repeated names there, for example.

Yes, you probably are right. In my field almost never happens (authors are at least shuffled around).... So I never saw it.

**Comment by moewew** [comment]
> In the end this is the IEEE's call, and it's what they do. I think it's not unreasonable to expect repeated names: in my area, you tend to cite a whole load of the work of one group in a block, so you'd see repeated names there, for example.

Sure. The IEEE decide. But I'm a bit confused that the only place where this dash replacement comes up is `IEEEtran.bst`).

I could not find a mention of it in the reference guidelines (at least the version I found https://ieeeauthorcenter.ieee.org/wp-content/uploads/IEEE-Reference-Guide.pdf) and it did not appear in the few IEEE journal papers I quickly had a look at this morning (I did some more digging, and not even in https://www.doi.org/10.1109/ACCESS.2020.3002183, where the PDF claims to be generated with LaTeX do we get dashes in 50 & 51 as well as 69 & 70). I also checked the IEEE CSL style (https://github.com/citation-style-language/styles/blob/master/ieee.csl) and it does not appear to use dashes either (I don't speak CSL, but from https://forums.zotero.org/discussion/752/csl-long-dashes-for-repeated-bibliography-entries/ I gather we should see a `subsequent-author-substitute` somewhere if it did).

**Comment by josephwright** [comment]
@moewew The thing is that `IEEEtran.bst` is an official style, and uses dashes, so I assume this was approved by the publisher

**Comment by moewew** [comment]
Yeah, the official status of `IEEEtran.bst` is why I don't want to simply disregard what it does. I sent an email to the maintainer of `IEEEtran.bst` about this. Maybe he can help out. (Maybe the IEEE changed policies here: The version of IEEEtran on CTAN is from 2015, the style guide we found from 2018.)

**Comment by moewew** [comment]
I received a reply from Michael. He told me that the IEEEtran behaviour was copied from journal publications at the time and that he had not been made aware of a change in policy there on the IEEE side.

Given from what I have seen in IEEE publications I'd no go with the dash, but I admit that my willingness to draw that conclusion from my observations is influenced by my thinking that dashes are a bit weird in a unsorted (numeric) bibliography.

**Comment by josephwright** [comment]
OK, I'll look to do a release.
