### ISSUE TITLE
incorrect book series formatting

### ISSUE THREAD

**Issue by jacobmerson** [josephwright/biblatex-ieee#63]
A book chapter with a series is supposed to be in parentheses after the italicized book name. Currently, it is written as "ser. series name".

See page 5 of the [ieee reference guide](http://journals.ieeeauthorcenter.ieee.org/wp-content/uploads/sites/7/IEEE-Reference-Guide-Online-v.04-20-2021.pdf)

**Comment by AlMa1r** [comment]
The link is gone; I cannot verify this information. @jacobmerson , @josephwright Could I kindly ask you to update the link and provide the quotation here verbatim for future uses? I was surprised to stumble into a silent change when recompiling an old document of mine, and it took me quite a long to find this very issue report.

**Comment by josephwright** [comment]
@AlMa1r  If you believe there is problem, please log a new issue

**Comment by AlMa1r** [comment]
@josephwright No or not yet. I discovered the change (cf. https://tex.stackexchange.com/questions/708583) and started wondering whether there is a problem.

**Comment by AlMa1r** [comment]
@jacobmerson Thx! For clarification, my use case would correspond to
M. Abramowitz and I. A. Stegun, Eds., _Handbook of Mathematical Functions_ (Applied Mathematics Series 55). Washington, DC, USA: NBS, 1964, pp. 32–33.
