### ISSUE TITLE
periodicals should not include day

### ISSUE THREAD

**Issue by jacobmerson** [josephwright/biblatex-ieee#64]
Periodicals should list the month and year, but should not include the day. Conference proceedings, patents, etc. do include the day.

See the [ieee reference guide](http://journals.ieeeauthorcenter.ieee.org/wp-content/uploads/sites/7/IEEE-Reference-Guide-Online-v.04-20-2021.pdf) page

**Comment by josephwright** [comment]
@moewew Is there a simple 'date format per entry type' function? I don't remember one ...

**Comment by moewew** [comment]
Unfortunately, there is no interface yet for per-type date settings. I looked at this a while ago, but there were difficulties with the interface as well as a possible implementation. Thoughts are always welcome. See https://github.com/plk/biblatex/issues/863.

For now you can use the internal implementation of the date formats, e.g. https://github.com/michal-h21/biblatex-iso690/blob/86fd078483eabd7ee929a872a309547a1ecc5179/iso.bbx#L512-L515 or https://tex.stackexchange.com/a/419719/35864 (look for `\changedateformat`). Of course this uses internals which may not be as stable as a simple option.

If you only need to get rid of the day for some types you can of course use the old `\clearfield` approach.

**Comment by josephwright** [comment]
@moewew  Thanks: what I thought

I'm reluctant to 'force' dropping of data by adding `\clearfield` to the style - that's irreversible so users can't override it (say if they have a newspaper article or similar that _does_ need the day). Probably therefore one for the docs: a lot of people will only have the day in when they _need_ it anyway.
