### ISSUE TITLE
space between two em dashes

### ISSUE THREAD

**Issue by jorsn** [josephwright/biblatex-ieee#66]
In some fonts like Libertinus (loaded with libertinus-otf), there is a space between the two em dashes, which are used here for abbreviating repeated authors in the bibliography. They are defined by
https://github.com/josephwright/biblatex-ieee/blob/7f67eea42f55ee0c27c8358dd7cd64bf47ad4a4c/ieee.bbx#L59

The reason is that there is no proper 2em-dash (U+2E3A) in LaTeX. Also, in some fonts (e.g. Libertinus) this symbol is missing.
IEEEtran.bst also uses '------', which is the same as `\textemdash\textemdash`.

To solve this, one could improvise an (almost) proper 2em dash. Only: How broad is proper?

![dashes](https://user-images.githubusercontent.com/4646725/194123241-d29ee2ba-e946-4e96-b2fe-05747f4ea84d.svg)

<details>
<summary>(compiled with pdfLaTeX/TeXlive 2021. expand to view the TeX-code for the table)</summary>

The macro `\longdash` was stolen from https://tex.stackexchange.com/a/83988.

~~~tex
\documentclass[12pt]{standalone}

\usepackage[T1]{fontenc}
\usepackage{times}
\usepackage{microtype}

\begin{document}


\newcommand*{\longdash}[1]{%
\makebox[#1]{%
  \rlap{\textemdash}\kern.5em
  \cleaders\hbox{\kern-.3em\textemdash\kern-.3em}\hfill\kern.5em
  \llap{\textemdash}}%
}

\begin{tabular}{l l}
  A\textemdash\textemdash,
    & \verb|A\textemdash\textemdash,|
    \\
  A------,
    & \verb|A------,|
    \\
  A\textemdash\rlap{\kern-.4em\textemdash}\textemdash,
    & \verb|A\textemdash\rlap{\kern-.4em\textemdash}\textemdash,|
    \\
  AMM \\
  A\longdash{2\fontcharwd\font`M},
    & \verb|A\longdash{2\fontcharwd\font`M},|
    \\
  A\longdash{2em},
    & \verb|A\longdash{2em},|
    \\
  A\rule{2em}{0.5pt},
    & \verb|A\rule{2em}{0.5pt},|
\end{tabular}

\end{document}

~~~
</details>

<details>
<summary>(expand to see the table in Computer Modern and Times)</summary>

Computer Modern (default T1 font)

![dashes](https://user-images.githubusercontent.com/4646725/194123274-b139d8c9-5f3a-41d3-a257-017e38e8de17.svg)

Times (used by IEEEtran)

![dashes](https://user-images.githubusercontent.com/4646725/194123390-a821427e-63e1-49f1-b65f-24b03bd889ce.svg)
</details>

**Comment by josephwright** [comment]
I think this is a font-design decision: the symbol used is two em-dashes, if they don't touch that's not really 'my fault'.
