### ISSUE TITLE
How to modify space between bibliography entry number and the entry contents?

### ISSUE THREAD

**Issue by pwintz** [josephwright/biblatex-ieee#68]
After I switched to using BibLaTeX with the IEEE style, my advisor complained that there is too much space between the entry number and entry content in the bibliography. Is there an easy way to change that spacing?

The spacing below "References" is also different, so I'd also like to know how to adjust that, if possible. 

**BibTeX Bibliography**
![image](https://github.com/josephwright/biblatex-ieee/assets/19618780/1bc51d5f-5d58-450d-8b84-13fb2c5c93b8)

**BibLaTeX Bibliography**
![image](https://github.com/josephwright/biblatex-ieee/assets/19618780/23f52bb5-c4d7-45f7-8529-ba01786b7795)

**Comment by josephwright** [comment]
General questions, rather than issues, should be raised on a forum such as [TeX-sx](https://tex.stackexchange.com/) - this is about how the bibliography environment is set up, rather than a bug in `biblatex-ieee`.

**Comment by pwintz** [comment]
Got it. I've posted the question [here](https://tex.stackexchange.com/questions/694296/how-to-change-space-between-numbers-and-entries-in-biblatex-using-style-ieee).

There does seem to be a common expectation that the IEEE BibLaTeX style would set things like the font size and spacing, so it might be worth adding a clarification to the README.
