### ISSUE TITLE
Compressed Citations

### ISSUE THREAD

**Issue by marvin-te** [josephwright/biblatex-ieee#69]
Hello there,

As of last year, the [IEEE Reference Guide](https://journals.ieeeauthorcenter.ieee.org/wp-content/uploads/sites/7/IEEE_Reference_Guide.pdf) changed, in a way that discurages the use of compressed citations in the style of `[2]-[5]`:

> Reference ranges in text will not include an en dash. All references will be written out. For example, “[1]–[4]” will
now be “[1], [2], [3], [4]”

_(p. 4, end of section A of above reference guide)_

I tried your workaround documented in 5b16b55, but sadly it did not work for me, resulting in the following error message:
```
! Package biblatex Error: Bibliography macro 'cite' undefined.
```

The relevent parts of my preamble look like this:
```latex
\RequirePackage{csquotes, url}
\RequirePackage[urldate=short, style=ieee]{biblatex} % IEEE-Zitierstil

\DeclareCiteCommand{\cite}
  {\bibopenbracket\usebibmacro{prenote}}
  {\usebibmacro{citeindex}%
   \usebibmacro{cite}}
  {\multicitedelim}
  {\usebibmacro{postnote}\bibclosebracket}
\renewcommand*\multicitedelim{\bibclosebracket\addcomma \space\bibopenbracket}

\renewcommand*{\bibfont}{\footnotesize} % Adjust the bibliography font size
\addbibresource{quellen.bib}
```

Sadly, I am too unfimiliar with the specifics behind biblatex to get behind this problem myself.
Also, as the official reference guide specifies the use of the uncompressed form, I would honestly assume that to be the default behaviour of this package, not needing such a workaround in the first place.

I hope you can help me with my issue and/or update the behaviour in the package.

Kind Regards

**Comment by bolu61** [comment]
You are missing `citestyle=numeric` in the biber package options.

**Comment by marvin-te** [comment]
Thanks for the clarification, that way it works.

Maybe this could be more clear from the documentation or - like I mentioned before - the package could be updated to adhere to the IEEE standard by default (maybe with a simple toggle option, if one wants to change back to compressed cites)?

**Comment by bolu61** [comment]
I think the default behaviour should be to not compress the citations to reflect the official style guidelines. @josephwright, maybe there could be a separate style variant?

**Comment by bolu61** [comment]
Thanks for the quick patch! 🫡
